### ISSUE TITLE
Failing mount of TRD on drive D

### ISSUE THREAD

**Issue by mborik** [mborik/speccy2010-dividised#3]
_Originally posted by @azesmbog in https://github.com/mborik/speccy2010/issues/1_
Please check how the D drive works.
Disk image is mounted ok, but it isn't visible in the commander and boot.
Drive A, B, and C are all good.

**Comment by azesmbog** [comment]
Yet this is not a bug, but a feature of TR-DOS 6.10
It can be assumed that the D drive in this version is reserved for the electronic RAM disk.
If you replace TR-DOS with the standard version 5.03, then everything works fine.
Just drive D apparently no one ever used on the Speccy2010, it was not necessary, but I accidentally checked.

**Comment by mborik** [comment]
thank you, so I closing this issue if it's not a bug
